implementado testes unitarios do login
agendasus/agendasus-auth pull request #3
Opened 2020-12-20 14:28 UTC by vinigomes

implementado os testes unitarios da classe login e ajustado os testes do controller do access recovery

2020-12-20 20:55 UTC, paulophgf commented on src/test/java/br/com/agendasus/auth/v1/domain/usecase/LoginTest.java
> +    public void checkAuthorizationWhenUserIsNotAdminAndIsNotTheSameUserRequest() {
Por que a nomenclatura dos métodos do LoginTest estão diferentes do AccessControllerTest? É para ser assim mesmo?

2020-12-20 20:57 UTC, paulophgf commented on src/test/java/br/com/agendasus/auth/v1/domain/usecase/LoginTest.java
> +    private UserLogin getMockedUser(String userName, UserType type) {
Levando em consideração o tamanho do módulo, acredito que não seja um problema deixar este método de factory de entidade aqui junto aos métodos de testes, mas podemos adotar um padrão de separar esses métodos em outra classe ou pacote, certo?

2020-12-20 21:06 UTC, paulophgf requested changes
Por favor, verifique os 3 comentários.

2020-12-20 21:06 UTC, paulophgf commented on src/test/java/br/com/agendasus/auth/v1/AccessRecoveryControllerTest.java
> +        this.mockMvc.perform(post("/forgot-password")
Não consegui indetificar se este teste se limita apenas ao escopo do controller, caso não, acredito que isso possa ativar o envio de email. E joao@gmail.com é um email válido que não está no nosso controle, ou seja, alguém vai recever este email e não vai entender sua origem. Neste caso, aconselho utilizarmos um email próprio para este fim, como agendasustestes@gmail.com.

2020-12-21 11:49 UTC, vinigomes commented on src/test/java/br/com/agendasus/auth/v1/domain/usecase/LoginTest.java
> +    public void checkAuthorizationWhenUserIsNotAdminAndIsNotTheSameUserRequest() {
Porque o método do Controller era apenas uma tentativa de teste de API, queria experimentar novos formatos de nomenclatura de testes para ver qual ficava melhor com relação a legibilidade, snake_case ou camelCase. O que você preferiu?

2020-12-21 11:51 UTC, vinigomes commented on src/test/java/br/com/agendasus/auth/v1/domain/usecase/LoginTest.java
> +    private UserLogin getMockedUser(String userName, UserType type) {
Com certeza, podemos criar classes de cenário.
Eu normalmente quando começo a desenvolver deixo na mesma classe para ficar fácil e rápido a legibilidade para fazer os asserts. Mas depois que o teste está feito acho que o custo é minimo de ir até a classe de cenário para verificar os valores.
Qual formato acreditas que podemos adotar?

2020-12-21 11:55 UTC, vinigomes commented on src/test/java/br/com/agendasus/auth/v1/AccessRecoveryControllerTest.java
> +        this.mockMvc.perform(post("/forgot-password")
Perfeita a sugestão, podemos até utilizar aquele e-mail do agendasus que criamos no gmail.

É que quando iniciei esses testes de Controller (API) eu desejava que eles fossem testes unitários, então o meu plano para os e-mails era utilizar um greenmail para mockar o envio de email.

No entanto, no decorrer do desenvolvimento ele acabou se tornando um teste de integração (serviço).
Mas ainda está aberta a decisão quanto o formato desses testes de API. Se tiver alguma opinião/sugestão, podemos experimentar. Até mesmo porque se batermos o martelo que esse cara sera um teste de serviço, precisaremos criar um ambiente com banco de dados para ele rodar.

2021-01-17 22:44 UTC, paulophgf commented on src/test/java/br/com/agendasus/auth/v1/domain/usecase/LoginTest.java
> +    public void checkAuthorizationWhenUserIsNotAdminAndIsNotTheSameUserRequest() {
Como o nome dos métodos são grandes acredito que separado pro underscore ( _ ) fique melhor.

2021-01-17 22:45 UTC, paulophgf commented on src/test/java/br/com/agendasus/auth/v1/domain/usecase/LoginTest.java
> +    private UserLogin getMockedUser(String userName, UserType type) {
Deixa a gente ter mais testes e a gente decide qual formato adotar. Se não tiver muito teste, não vejo problema em deixar na classe.

2021-01-17 22:49 UTC, merged